# Generated by Django 2.2 on 2019-05-05 00:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.DateField(null=True)),
                ('cvn', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('cardholder', models.CharField(max_length=200, null=True, unique=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useracc_id', to='jammin.UserAccount')),
                ('useraccounts', models.ManyToManyField(to='jammin.UserAccount')),
            ],
            options={
                'unique_together': {('user_account', 'cardholder')},
            },
        ),
    ]
