# Generated by Django 2.2 on 2019-05-02 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0002_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='wage',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammin.Item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jammin.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='store',
            field=models.ManyToManyField(through='jammin.Sells', to='jammin.Item'),
        ),
    ]
