# Generated by Django 2.2 on 2019-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0002_auto_20190430_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
